### PR TITLE
Done this as you want

### PR DESCRIPTION
**Pull request by aadityasivaS**
This time I did as you wanted 
This should be run like this
`node server.js [PORT_NUMBER]`

### CODE REVIEW

**Comment by aadityasivaS** [comment]
hello

**Comment by agent255** [comment]
> This time I did as you wanted
> This should be run like this
> `node server.js [PORT_NUMBER]`

Bro this is to be run without the port...... that's why it asks for port... it's only made for me... I don't expect many ppl to use.... especially with nodemon

**Review by agent255 — CHANGES_REQUESTED** [review]
Bro this is to be run **_without_** the port...... that's why it asks for port... it's only made for me... I don't expect many ppl to use.... especially with nodemon

**Comment by aadityasivaS** [comment]
Okay so I am closing it

**Pull request closed without merging**
